"""Initial migration: create all tables

Revision ID: 932d3601ea80
Revises: 
Create Date: 2025-11-06 12:55:12.008619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '932d3601ea80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_sid', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', postgresql.ENUM('tenant', 'owner', name='userrole'), nullable=True),
    sa.Column('status', postgresql.ENUM('active', 'completed', 'abandoned', name='callsessionstatus'), nullable=False),
    sa.Column('current_step', sa.String(), nullable=True),
    sa.Column('context_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_sessions_call_sid'), 'call_sessions', ['call_sid'], unique=True)
    op.create_index(op.f('ix_call_sessions_id'), 'call_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_call_sessions_phone_number'), 'call_sessions', ['phone_number'], unique=False)
    op.create_index(op.f('ix_call_sessions_status'), 'call_sessions', ['status'], unique=False)
    op.create_table('property_searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('search_criteria', sa.JSON(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_searches_id'), 'property_searches', ['id'], unique=False)
    op.create_index(op.f('ix_property_searches_phone_number'), 'property_searches', ['phone_number'], unique=False)
    op.create_table('property_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='unique_user_property_favorite')
    )
    op.create_index(op.f('ix_property_favorites_id'), 'property_favorites', ['id'], unique=False)
    # Crear ENUM para inquiries
    inquiry_status_enum = postgresql.ENUM('pending', 'responded', 'closed', name='inquirystatus', create_type=True)
    inquiry_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('inquiries', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('inquiries', sa.Column('preferred_contact_time', sa.String(), nullable=True))
    op.add_column('inquiries', sa.Column('status', inquiry_status_enum, nullable=True))
    op.add_column('inquiries', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Actualizar valores por defecto
    op.execute("UPDATE inquiries SET status = 'pending' WHERE status IS NULL")
    
    # Hacer status NOT NULL
    op.alter_column('inquiries', 'status', nullable=False)
    op.alter_column('inquiries', 'message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('inquiries', 'property_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_inquiries_status'), 'inquiries', ['status'], unique=False)
    op.create_foreign_key(None, 'inquiries', 'users', ['user_id'], ['id'])
    # Crear los ENUMs primero
    property_type_enum = postgresql.ENUM('apartment', 'house', 'studio', 'townhouse', 'condo', name='propertytype', create_type=True)
    property_type_enum.create(op.get_bind(), checkfirst=True)
    property_status_enum = postgresql.ENUM('available', 'rented', 'unavailable', name='propertystatus', create_type=True)
    property_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('properties', sa.Column('title', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('properties', sa.Column('city', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('neighborhood', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('zip_code', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('property_type', property_type_enum, nullable=True))
    op.add_column('properties', sa.Column('bedrooms', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('bathrooms', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('square_meters', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('deposit', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('status', property_status_enum, nullable=True))
    op.add_column('properties', sa.Column('pet_friendly', sa.Boolean(), nullable=True))
    op.add_column('properties', sa.Column('furnished', sa.Boolean(), nullable=True))
    
    # Actualizar valores por defecto para registros existentes
    # Si existe la columna 'name', usarla; si no, usar un valor por defecto
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.columns 
                      WHERE table_name='properties' AND column_name='name') THEN
                UPDATE properties SET title = COALESCE(name, 'Sin título') WHERE title IS NULL;
            ELSE
                UPDATE properties SET title = 'Sin título' WHERE title IS NULL;
            END IF;
        END $$;
    """)
    op.execute("UPDATE properties SET city = 'Ciudad no especificada' WHERE city IS NULL")
    op.execute("UPDATE properties SET property_type = 'apartment' WHERE property_type IS NULL")
    op.execute("UPDATE properties SET bedrooms = 1 WHERE bedrooms IS NULL")
    op.execute("UPDATE properties SET bathrooms = 1 WHERE bathrooms IS NULL")
    op.execute("UPDATE properties SET status = 'available' WHERE status IS NULL")
    op.execute("UPDATE properties SET pet_friendly = false WHERE pet_friendly IS NULL")
    op.execute("UPDATE properties SET furnished = false WHERE furnished IS NULL")
    
    # Ahora hacer las columnas NOT NULL
    op.alter_column('properties', 'title', nullable=False)
    op.alter_column('properties', 'city', nullable=False)
    op.alter_column('properties', 'property_type', nullable=False)
    op.alter_column('properties', 'bedrooms', nullable=False)
    op.alter_column('properties', 'bathrooms', nullable=False)
    op.alter_column('properties', 'status', nullable=False)
    op.alter_column('properties', 'pet_friendly', nullable=False)
    op.alter_column('properties', 'furnished', nullable=False)
    op.add_column('properties', sa.Column('amenities', sa.JSON(), nullable=True))
    op.add_column('properties', sa.Column('images', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('properties', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('longitude', sa.Float(), nullable=True))
    op.alter_column('properties', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_properties_city'), 'properties', ['city'], unique=False)
    op.create_index(op.f('ix_properties_neighborhood'), 'properties', ['neighborhood'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_index(op.f('ix_properties_status'), 'properties', ['status'], unique=False)
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=True))
    
    # Actualizar valores por defecto para usuarios existentes
    # Generar números de teléfono únicos para usuarios que no tienen uno
    op.execute("""
        UPDATE users 
        SET phone_number = '+000000000' || LPAD(id::text, 4, '0')
        WHERE phone_number IS NULL
    """)
    op.execute("UPDATE users SET is_active = true WHERE is_active IS NULL")
    
    # Crear ENUM para users si no existe
    user_role_enum = postgresql.ENUM('tenant', 'owner', name='userrole', create_type=True)
    user_role_enum.create(op.get_bind(), checkfirst=True)
    
    # Hacer las columnas NOT NULL
    op.alter_column('users', 'phone_number', nullable=False)
    op.alter_column('users', 'is_active', nullable=False)
    
    # Convertir role de VARCHAR a ENUM
    # Primero eliminar el valor por defecto, luego cambiar el tipo, luego agregar el nuevo default
    op.execute("ALTER TABLE users ALTER COLUMN role DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN role TYPE userrole USING role::userrole")
    op.execute("ALTER TABLE users ALTER COLUMN role SET DEFAULT 'tenant'::userrole")
    op.alter_column('users', 'role', nullable=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('tenant', 'owner', name='userrole'),
               type_=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'tenant'::character varying"))
    op.drop_column('users', 'preferences')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'phone_number')
    op.drop_index(op.f('ix_properties_status'), table_name='properties')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_neighborhood'), table_name='properties')
    op.drop_index(op.f('ix_properties_city'), table_name='properties')
    op.alter_column('properties', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('properties', 'longitude')
    op.drop_column('properties', 'latitude')
    op.drop_column('properties', 'images')
    op.drop_column('properties', 'amenities')
    op.drop_column('properties', 'furnished')
    op.drop_column('properties', 'pet_friendly')
    op.drop_column('properties', 'status')
    op.drop_column('properties', 'deposit')
    op.drop_column('properties', 'square_meters')
    op.drop_column('properties', 'bathrooms')
    op.drop_column('properties', 'bedrooms')
    op.drop_column('properties', 'property_type')
    op.drop_column('properties', 'zip_code')
    op.drop_column('properties', 'neighborhood')
    op.drop_column('properties', 'city')
    op.drop_column('properties', 'description')
    op.drop_column('properties', 'title')
    op.drop_constraint(None, 'inquiries', type_='foreignkey')
    op.drop_index(op.f('ix_inquiries_status'), table_name='inquiries')
    op.alter_column('inquiries', 'property_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('inquiries', 'message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('inquiries', 'user_id')
    op.drop_column('inquiries', 'status')
    op.drop_column('inquiries', 'preferred_contact_time')
    op.drop_column('inquiries', 'phone_number')
    op.drop_index(op.f('ix_property_favorites_id'), table_name='property_favorites')
    op.drop_table('property_favorites')
    op.drop_index(op.f('ix_property_searches_phone_number'), table_name='property_searches')
    op.drop_index(op.f('ix_property_searches_id'), table_name='property_searches')
    op.drop_table('property_searches')
    op.drop_index(op.f('ix_call_sessions_status'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_phone_number'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_call_sid'), table_name='call_sessions')
    op.drop_table('call_sessions')
    # ### end Alembic commands ###
